kind: pipeline
name: default
steps:

- name: build image  
  image: plugins/docker
  settings:
    repo: nwd.me/ddns
    tags: [ latest ]
    registry: nwd.me
    username: { from_secret: docker_username }
    password: { from_secret: docker_password }

- name: deploy
  image: peloton/drone-rancher
  settings:
    docker_image: nwd.me/ddns
    service: edge/updater-dns
    url: http://node:8080/v1
    access_key: { from_secret: rancher_access_key }
    secret_key: { from_secret: rancher_secret_key }
    confirm: true
